export default {
    NumPad: {
        MAX: 'Максимум',
        CURRENT_BONUS_QUANTITY: 'Будет списано',
        QUANTITY_NUMPAD: 'Количество',
        GUESTS_QUANTITY: 'Количество гостей',
        SUM_NUMPAD: 'Сумма',
        WEIGH_NUMPAD: 'Взвесить',
        APPLY: 'Применить',
        ONE: '1',
        TWO: '2',
        THREE: '3',
        FOUR: '4',
        FIVE: '5',
        SIX: '6',
        SEVEN: '7',
        EIGHT: '8',
        NINE: '9',
        ZERO: '0',
        DOT: '.',
        COMMA: ',',
        CLEAR: 'C',
        OK: 'OK',
        MEASURE_PIECES: 'шт',
    }
};
